[build]
functions = "netlify/functions"
publish = "dist"
command = "npx vite build"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200